# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
# title:            Hyde
# tagline:          'A Jekyll theme'
# description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
# baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


theme: jekyll-theme-slate
google_analytics: UA-119137376-1

title: Taskette
tagline: A scheduled service
description: Articles and guides for Taskette users
url: https://blog.taskette.io
logo: /logo.png

plugins:
  - jekyll-seo-tag
